default: &default
  adapter: postgresql
  encoding: unicode
  # Puma: 3 threads × 1 worker = 3 connections
  # GoodJob: 5 queue threads + 3 system threads = 8 connections
  # Buffer: 5 additional connections
  # Total: 16 connections
  pool: <%= ENV.fetch("DB_POOL_SIZE") { 16 } %>
  host: <%= ENV.fetch("DB_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DB_PORT") { "5432" } %>
  user: <%= ENV.fetch("POSTGRES_USER") { nil } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { nil } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "maybe_production" } %>
